In [6]:
import numpy as np 

In [7]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,77])

In [21]:
#1.有多少學生英文成績比數學成績高?
a = np.greater(english_score,math_score)
print (np.sum(a==True))
##有三個True，代表有三位同學英文成績比數學高

3


In [16]:
#2.是否全班同學最高分都是國文?
b = np.greater(chinese_score,english_score)
b

array([ True,  True,  True,  True,  True,  True])

In [17]:
c = np.greater(chinese_score,math_score)
c

array([ True,  True,  True,  True,  True,  True])

In [18]:
np.logical_and(b,c)
##皆為True代表全班國文分數皆大於數學及英文，及最高分為國文

array([ True,  True,  True,  True,  True,  True])