In [5]:
import numpy as np

In [13]:
array1 = np.array(range(30),order = 'F')
array2 = array1.reshape(5,6)
print(array2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [15]:
np.where(array2 % 6 ==1)

(array([0, 1, 2, 3, 4], dtype=int64), array([1, 1, 1, 1, 1], dtype=int64))